"use client";

import { ArrowLeft, BookOpen, ClipboardList, AlertCircle, Copy } from "lucide-react";
import type { NavigateProps } from "@/lib/islamind-types";

const reflectionSections = [
  {
    emoji: "💛",
    title: "Emotional summary",
    content: (
      <p className="text-muted-foreground text-sm leading-[1.7]">
        Your entry reflects a mix of{" "}
        <strong className="text-foreground">anxiety and motivation</strong>. You
        seem to be carrying a heavy load right now — the weight of upcoming exams
        — while also showing real resourcefulness by actively looking for
        strategies to cope.
      </p>
    ),
  },
  {
    emoji: "🔍",
    title: "Possible theme",
    content: (
      <>
        <div className="px-3 py-2 rounded-xl bg-secondary mb-2">
          <p className="text-primary text-[13px] font-semibold">
            Pressure vs. self-compassion
          </p>
        </div>
        <p className="text-muted-foreground text-sm leading-[1.7]">
          It sounds like you&apos;re navigating a tension between wanting to
          perform well and feeling the weight of too many demands at once. This is
          a common experience during high-stakes periods.
        </p>
      </>
    ),
  },
  {
    emoji: "❓",
    title: "Reflective question",
    content: (
      <p
        className="text-foreground pl-3 border-l-2 border-primary text-[15px] leading-[1.7] italic"
      >
        &quot;If a close friend came to you with exactly the same situation, what
        would you tell them? Would you speak to yourself the same way?&quot;
      </p>
    ),
  },
  {
    emoji: "🌱",
    title: "A small action",
    content: (
      <>
        <p className="text-muted-foreground text-sm leading-[1.7] mb-3">
          Based on what you shared, one small, manageable action for today might
          be:
        </p>
        <div className="bg-background rounded-xl px-4 py-3 border border-border">
          <p className="text-foreground text-sm leading-relaxed">
            Spend 10 minutes writing out your three most important exam tasks in
            order of priority. Not starting them — just listing them. Sometimes
            naming the load makes it feel lighter.
          </p>
        </div>
        <p className="text-muted-foreground mt-3 text-[12px] leading-relaxed">
          This is a suggestion, not a prescription. Do only what feels right for
          you.
        </p>
      </>
    ),
  },
];

export function AIReflectionScreen({ navigate }: NavigateProps) {
  return (
    <main className="min-h-screen bg-background pb-8">
      {/* Header */}
      <header className="flex items-center gap-3 px-5 pt-14 pb-2">
        <button
          onClick={() => navigate("journal-list")}
          className="w-9 h-9 rounded-xl bg-card border border-border flex items-center justify-center"
          aria-label="Go back"
        >
          <ArrowLeft size={18} className="text-foreground" aria-hidden="true" />
        </button>
        <h1 className="text-foreground font-bold" style={{ fontSize: 17 }}>
          AI Reflection
        </h1>
        <button
          className="ml-auto w-9 h-9 rounded-xl bg-card border border-border flex items-center justify-center"
          aria-label="Copy reflection"
        >
          <Copy size={15} className="text-muted-foreground" aria-hidden="true" />
        </button>
      </header>

      <div className="px-5">
        {/* Context badge */}
        <div className="flex items-center gap-2 py-3 mb-2">
          <div className="w-7 h-7 rounded-lg bg-primary flex items-center justify-center flex-shrink-0">
            <span style={{ fontSize: 14 }} aria-hidden="true">✨</span>
          </div>
          <div>
            <p className="text-foreground text-[13px] font-semibold">
              Reflection for &quot;Processing exam stress&quot;
            </p>
            <p className="text-muted-foreground text-[11px]">
              Today, 9:14 AM · Mood 7/10
            </p>
          </div>
        </div>

        {/* Disclaimer */}
        <div
          className="bg-[#FFF8F0] border border-[#F2B880]/50 rounded-xl px-4 py-3 mb-5 flex items-start gap-2"
          role="note"
          aria-label="AI disclaimer"
        >
          <AlertCircle
            size={15}
            className="text-[#B25C00] flex-shrink-0 mt-0.5"
            aria-hidden="true"
          />
          <p className="text-[#B25C00] text-[12px] leading-relaxed">
            This reflection is generated by AI. It is not professional advice,
            diagnosis, or therapy. Use it only as a gentle thinking aid.
          </p>
        </div>

        {/* Reflection sections */}
        <div className="space-y-3">
          {reflectionSections.map((section) => (
            <div
              key={section.title}
              className="bg-card rounded-2xl p-4 border border-border"
            >
              <div className="flex items-center gap-2 mb-2">
                <span style={{ fontSize: 16 }} aria-hidden="true">
                  {section.emoji}
                </span>
                <p className="text-foreground text-[13px] font-bold">
                  {section.title}
                </p>
              </div>
              {section.content}
            </div>
          ))}
        </div>

        {/* Actions */}
        <div className="flex gap-3 mt-6">
          <button
            onClick={() => navigate("journal-editor")}
            className="flex-1 h-12 rounded-2xl bg-secondary text-primary flex items-center justify-center gap-2 hover:bg-secondary/80 transition-colors font-semibold text-sm"
          >
            <BookOpen size={16} aria-hidden="true" />
            Write more
          </button>
          <button
            onClick={() => navigate("cbt")}
            className="flex-1 h-12 rounded-2xl border border-border bg-card text-foreground flex items-center justify-center gap-2 hover:bg-background transition-colors font-medium text-sm"
          >
            <ClipboardList size={16} aria-hidden="true" />
            CBT record
          </button>
        </div>

        {/* Safety footer */}
        <div className="mt-6 px-4 py-3 rounded-xl bg-card border border-border">
          <p className="text-muted-foreground text-[11px] leading-relaxed text-center">
            If you are in distress, please reach out to a trusted person or
            emergency services.{" "}
            <button
              onClick={() => navigate("safety")}
              className="text-primary font-semibold underline"
            >
              See resources
            </button>
          </p>
        </div>
      </div>
    </main>
  );
}
